# SPDX-FileCopyrightText: 2025 2025 Frederic Ruget <fred@atlant.is>
#
# SPDX-License-Identifier: MIT

version = 1

[[annotations]]
path = "src/*"
SPDX-FileCopyrightText = "2006 Joachim Henke"
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = "./*"
SPDX-FileCopyrightText = "2025 Frederic Ruget <fred@atlant.is>"
SPDX-License-Identifier = "MIT"