# SPDX-FileCopyrightText: 2026 Frederic Ruget <fred@atlant.is> (GitHub: @douzebis)
#
# SPDX-License-Identifier: MIT

name: C

on:
  push:
    branches: [main]
    paths:
      - 'src/**'
      - 'default.nix'
      - '.github/workflows/c.yml'
  pull_request:
    paths:
      - 'src/**'
      - 'default.nix'
      - '.github/workflows/c.yml'

jobs:
  build:
    name: clang build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: cachix/install-nix-action@v31

      - uses: cachix/cachix-action@v17
        with:
          name: base91
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
        continue-on-error: true

      - name: build libbase91
        run: nix-build default.nix -A base91-clib
